[package]
name = "lobby_common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
uuid = { version = "1.16", features = ["v4", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
engine_common = { path = "../engine_common" }
